r_base:
  - "3.6.0"
  - "3.6.1"
  - "4.2.0"  # [not win]
  - "4.3.1"  # [not win]

# Pair R versions with compatible gfortran
libgfortran_ng:
  - "7"
  - "7"
  - "11"  # [not win]
  - "11"  # [not win]

# r-statmod only available for R 4.2+
with_statmod:
  - "false"
  - "false"
  - "true"  # [not win]
  - "true"  # [not win]

zip_keys:
  - [r_base, libgfortran_ng, with_statmod]

pin_run_as_build:
  r-base:
    min_pin: x.x
    max_pin: x.x
